### ISSUE TITLE
Async compression/decompression

### ISSUE THREAD

**Issue by unknown-gd** [WilliamVenner/gmod-lzma-rs#1]
I just noticed this https://github.com/Facepunch/garrysmod-requests/issues/2165 issue on the official garrysmod repository and remembered your repository, do you have any future plans to add asynchronous compression and decompression functionality to this binary module, I think it would be useful for some developers.

**Comment by WilliamVenner** [comment]
Hi, this is not actually a binary module for Gmod, but rather just simply a Rust library (crate). However, I do like the idea of an async compression module, and this library can be used to create it :)

**Comment by unknown-gd** [comment]
Oh, sorry I didn't notice, I just specialize mainly in Lua and languages that are compiled into it, I almost never worked with C++ and especially Rust, but about the module I already said above, in general I think Garry's Mod has a lot of things that should be asynchronous, but alas we are still waiting for the official file.AsyncWrite... anyway thanks for the reply)
